name: ChatGT3 CI Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: go mod download
      - name: Run Tests
        run: go test ./...
        env:
          CI: true
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
